# Escaped Asteroid Analysis
The run_log_analysis python script summarises the hdf5 log files into an escaped_asteroids pandas DataFrame. This DataFrame has details of the parameter and time that the asteroid exceeds the various parameters that are monitored.

In [2]:
import datetime as datetime

import pandas as pd
import numpy as np
import h5py as h5

import scipy
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:

# indices in the particles array 
A = 6
E = 7
I = 8

pa_mv3 = pd.read_hdf('../asteroid_data/sim_data/mv_3/inputs/clone_assignments.h5')
ea_mv3 = pd.read_hdf('../asteroid_data/sim_data/mv_3/escaped_asteroids')

pa_mvc3 = pd.read_hdf('../asteroid_data/sim_data/mvc_3/inputs/clone_assignments.h5')
ea_mvc3 = pd.read_hdf('../asteroid_data/sim_data/mvc_3/escaped_asteroids')

In [13]:
print(pa_mv3.sort_values(['sim_no', 'particle_number']).tail())
print(pa_mvc3.sort_values(['sim_no', 'particle_number']).tail())

       sim_no  particle_number    ast_name                     particle_types
57069   19021               11  2013 CR249              [X, Y, Z, VX, VY, VZ]
19022   19022                9      488807  [Xcm, Ycp, Zcm, VXcp, VYcm, VZcp]
38046   19022               10  2000 RV111  [Xcp, Ycm, Zcp, VXcm, VYcp, VZcm]
19023   19023                9      488807  [Xcm, Ycp, Zcm, VXcp, VYcm, VZcm]
38047   19023               10  2000 RV111  [Xcp, Ycm, Zcp, VXcm, VYcm, VZcp]
       sim_no  particle_number    ast_name                     particle_types
57069   19021               12  2013 CR249              [X, Y, Z, VX, VY, VZ]
19022   19022               10      488807  [Xcm, Ycp, Zcm, VXcp, VYcm, VZcp]
38046   19022               11  2000 RV111  [Xcp, Ycm, Zcp, VXcm, VYcp, VZcm]
19023   19023               10      488807  [Xcm, Ycp, Zcm, VXcp, VYcm, VZcm]
38047   19023               11  2000 RV111  [Xcp, Ycm, Zcp, VXcm, VYcm, VZcp]

In [5]:
gb_c = ea_mvc3.groupby(['parameter'])
gb_c.agg({'parameter_value' : [np.min,np.max]})

          parameter_value
                     amin      amax
parameter
6                0.000000  4.132220
7                0.503369  0.526321
8                0.819451  0.833718

In [19]:
print(f"Ceres Mercurious escaped asteroids:{(ea_mc3['ast_name']+ea_mc3['vectors']).nunique()}")

print(f"Venus Ceres Mercurious escaped asteroids:{(ea_mvc3['ast_name']+ea_mvc3['vectors']).nunique()}")

Ceres escaped asteroids:10
Ceres Mercurious escaped asteroids:6
Venus Ceres escaped asteroids:14
Venus Ceres Mercurious escaped asteroids:6

In [18]:
ea_c3.sort_values(by=['ast_name', 'vectors']).head(20)

,ast_name,vectors,sim_no,particle_number,parameter,parameter_value,integration_year
14,1303,XcpYcpZcmVXcmVYcmVZcp,14,9,6,4.473191,3.992095e+09
15,1303,XcpYcpZcmVXcmVYcmVZcp,14,9,7,0.502553,3.884550e+09
4,2000 RV111,XcmYcmZcmVXcmVYcpVZcm,38,11,6,4.652984,8.293823e+08
6,2000 RV111,XcmYcmZcmVXcmVYcpVZcm,38,11,7,0.504304,8.262224e+08
8,2000 RV111,XcmYcpZcmVXcmVYcpVZcp,21,11,6,4.940899,9.239922e+08
9,2000 RV111,XcmYcpZcmVXcmVYcpVZcp,21,11,7,0.500748,9.236718e+08
10,2000 RV111,XcmYcpZcmVXcmVYcpVZcp,21,11,8,0.800004,2.601243e+09
25,2000 RV111,XcmYcpZcpVXcmVYcpVZcp,13,11,6,4.514418,5.091962e+09
26,2000 RV111,XcmYcpZcpVXcmVYcpVZcp,13,11,7,0.509841,5.091673e+09
19,488807,XcmYcmZcpVXcmVYcmVZcp,10,10,6,164.021299,4.477627e+09
20,488807,XcmYcmZcpVXcmVYcmVZcp,10,10,7,0.503788,4.472846e+09
21,488807,XcmYcmZcpVXcmVYcmVZcp,10,10,8,0.809795,4.477438e+09
11,488807,XcmYcpZcmVXcmVYcpVZcp,0,10,6,4.574569,5.718982e+09
12,488807,XcmYcpZcmVXcmVYcpVZcp,0,10,7,0.513031,5.702654e+09
13,488807,XcmYcpZcmVXcmVYcpVZcp,0,10,8,0.814661,5.717656e+09
22,493333,XcpYcmZcpVXcmVYcpVZcp,41,10,6,4.306773,5.410118e+09
23,493333,XcpYcmZcpVXcmVYcpVZcp,41,10,7,0.510338,5.374736e+09
24,493333,XcpYcmZcpVXcmVYcpVZcp,41,10,8,1.353728,5.410218e+09
3,493333,XcpYcmZcpVXcpVYcpVZcm,38,10,6,76.453744,3.102141e+09
5,493333,XcpYcmZcpVXcpVYcpVZcm,38,10,7,0.520732,3.052801e+09

In [7]:
ea_mc3.sort_values(by=['ast_name', 'vectors']).head(20)

,ast_name,vectors,sim_no,particle_number,parameter,parameter_value,integration_year
4,1303,XcmYcpZcpVXcpVYcmVZcm,35,9,6,4.063738,4.686679e+09
6,1303,XcmYcpZcpVXcpVYcmVZcm,35,9,7,0.515806,4.655400e+09
7,1303,XcmYcpZcpVXcpVYcmVZcm,35,9,8,0.822130,4.686805e+09
8,1303,XcpYcpZcmVXcmVYcmVZcp,14,9,6,6.348296,3.805853e+09
10,1303,XcpYcpZcmVXcmVYcmVZcp,14,9,7,0.510191,3.804044e+09
5,2000 RV111,XcmYcmZcmVXcpVYcmVZcp,35,11,6,0.000000,4.687081e+09
9,2000 RV111,XcmYcpZcpVXcmVYcpVZcm,14,11,6,0.000000,3.805998e+09
1,2001 QO310,XcpYcpZcpVXcmVYcmVZcp,48,11,6,0.000000,3.733910e+09
0,493333,XcpYcmZcmVXcpVYcmVZcm,48,10,6,6.425520,3.733225e+09
2,493333,XcpYcmZcmVXcpVYcmVZcm,48,10,7,0.503606,3.707876e+09
3,493333,XcpYcmZcmVXcpVYcmVZcm,48,10,8,0.804033,3.730279e+09

In [8]:
ea_vc3.sort_values(by=['ast_name', 'vectors']).head(20)

,ast_name,vectors,sim_no,particle_number,parameter,parameter_value,integration_year
0,1303,XcmYcmZcpVXcpVYcpVZcp,48,10,6,6.793124,5.222334e+08
2,1303,XcmYcmZcpVXcpVYcpVZcp,48,10,7,0.519619,5.180055e+08
4,1303,XcmYcmZcpVXcpVYcpVZcp,48,10,8,0.800001,2.379036e+09
31,1303,XcmYcpZcmVXcmVYcmVZcm,47,10,6,6.884732,5.142968e+09
33,1303,XcmYcpZcmVXcmVYcmVZcm,47,10,7,0.501298,5.095719e+09
6,1303,XcmYcpZcmVXcmVYcpVZcp,44,10,6,4.959374,1.009813e+09
7,1303,XcmYcpZcmVXcmVYcpVZcp,44,10,7,0.546615,1.006239e+09
8,1303,XcmYcpZcmVXcmVYcpVZcp,44,10,8,0.800008,3.233652e+09
23,1303,XcpYcmZcmVXcpVYcpVZcm,25,10,7,0.501812,6.242722e+09
24,1303,XcpYcmZcmVXcpVYcpVZcm,25,10,8,0.805957,6.276086e+09
36,1303,XcpYcpZcpVXcmVYcpVZcm,5,10,6,4.870155,3.208656e+09
37,1303,XcpYcpZcpVXcmVYcpVZcm,5,10,7,0.512699,3.191078e+09
38,1303,XcpYcpZcpVXcmVYcpVZcm,5,10,8,0.804758,3.209240e+09
20,488807,XcmYcmZcmVXcmVYcpVZcp,16,11,6,-6.763696,3.903535e+09
21,488807,XcmYcmZcmVXcmVYcpVZcp,16,11,7,0.540063,3.888565e+09
22,488807,XcmYcmZcmVXcmVYcpVZcp,16,11,8,0.894705,3.903447e+09
9,488807,XcmYcmZcpVXcmVYcmVZcp,10,11,6,1.411125,1.982962e+09
10,488807,XcmYcmZcpVXcmVYcmVZcp,10,11,7,0.502654,1.977773e+09
11,488807,XcmYcmZcpVXcmVYcmVZcp,10,11,8,0.800026,3.332277e+09
14,488807,XcmYcpZcmVXcmVYcpVZcp,0,11,6,7.677545,5.911832e+09

In [9]:
ea_mvc3.sort_values(by=['ast_name', 'vectors']).head(20)

,ast_name,vectors,sim_no,particle_number,parameter,parameter_value,integration_year
8,1303,XcpYcmZcmVXcpVYcmVZcp,26,10,6,4.066917,5.262009e+09
10,1303,XcpYcmZcmVXcpVYcmVZcp,26,10,7,0.507063,5.250318e+09
11,1303,XcpYcmZcmVXcpVYcmVZcp,26,10,8,0.833212,5.261827e+09
0,1303,XcpYcmZcmVXcpVYcpVZcm,25,10,6,4.085326,5.180321e+09
2,1303,XcpYcmZcmVXcpVYcpVZcm,25,10,7,0.526321,5.150186e+09
3,1303,XcpYcmZcmVXcpVYcpVZcm,25,10,8,0.819451,5.179002e+09
9,2000 RV111,XcmYcmZcpVXcpVYcpVZcm,26,12,6,0.000000,5.266155e+09
1,2000 RV111,XcmYcmZcpVXcpVYcpVZcp,25,12,6,0.000000,5.182872e+09
5,2001 QO310,XcpYcpZcpVXcpVYcpVZcm,43,12,6,0.000000,5.260162e+09
4,493333,XcpYcmZcpVXcmVYcmVZcp,43,11,6,4.132220,5.258290e+09
6,493333,XcpYcmZcpVXcmVYcmVZcp,43,11,7,0.503369,5.181842e+09
7,493333,XcpYcmZcpVXcmVYcmVZcp,43,11,8,0.833718,5.258089e+09

In [21]:
ea_mc3.groupby(['parameter']).max()

,ast_name,vectors,sim_no,particle_number,parameter_value,integration_year
parameter,,,,,,
6,493333,XcpYcpZcpVXcmVYcmVZcp,48,11,6.425520,4.687081e+09
7,493333,XcpYcpZcmVXcmVYcmVZcp,48,10,0.515806,4.655400e+09
8,493333,XcpYcmZcmVXcpVYcmVZcm,48,10,0.822130,4.686805e+09

In [22]:
ea_mvc3.groupby(['parameter']).max()

,ast_name,vectors,sim_no,particle_number,parameter_value,integration_year
parameter,,,,,,
6,493333,XcpYcpZcpVXcpVYcpVZcm,43,12,4.132220,5.266155e+09
7,493333,XcpYcmZcpVXcmVYcmVZcp,43,11,0.526321,5.250318e+09
8,493333,XcpYcmZcpVXcmVYcmVZcp,43,11,0.833718,5.261827e+09

In [42]:
ea_vc1.groupby(['ast_name', 'vectors']).size()

ast_name  vectors
2016 LZ6  XYZVXVYVZ                3
          XcmYcmZcmVXcmVYcmVZcp    3
          XcmYcmZcmVXcpVYcmVZcm    2
          XcmYcmZcmVXcpVYcmVZcp    3
          XcmYcmZcmVXcpVYcpVZcm    3
          XcmYcmZcmVXcpVYcpVZcp    3
          XcmYcmZcpVXcmVYcpVZcm    3
          XcmYcmZcpVXcmVYcpVZcp    3
331978    XcmYcmZcmVXcmVYcmVZcm    3
          XcmYcmZcmVXcmVYcmVZcp    3
          XcmYcmZcmVXcmVYcpVZcm    3
          XcmYcmZcmVXcmVYcpVZcp    3
          XcmYcmZcmVXcpVYcmVZcm    3
          XcmYcmZcpVXcmVYcmVZcm    3
          XcmYcmZcpVXcmVYcmVZcp    3
          XcmYcmZcpVXcmVYcpVZcp    3
          XcmYcmZcpVXcpVYcmVZcp    3
          XcmYcmZcpVXcpVYcpVZcm    3
          XcmYcmZcpVXcpVYcpVZcp    3
          XcmYcpZcmVXcpVYcmVZcm    3
          XcmYcpZcmVXcpVYcmVZcp    3
          XcmYcpZcmVXcpVYcpVZcm    3
          XcmYcpZcmVXcpVYcpVZcp    3
dtype: int64